import Head from 'next/head';
import Navbar from '../components/Navbar';
import { Main } from '../components/Main';
import About from '../components/About';
import Projects from '../components/Projects';
import { Contact } from '../components/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yasmine | Developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Projects />
      <Contact />
    </div>
  );
}
